---
- name: restart apache
  #  (excluding case when docker container)
  service:
    name: apache2
    state: "{{ 'stopped' if 'container' in group_names else 'restarted' }}"
  when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'